* Spesifikasjon for interface med ekstern hardware

** Fysiske dimensjoner og anbefalt bygging

*** Bygging
- En 2t4 på høykant på hver side
- Dekket med 6mm kryssfiner over hele, trekk dekket helt til endes
- 40cm bred plate midten for kontakter, bestående av 3 stykk 4mm kryssfinerplate limt sammen , 5cm inn fra tuppen må lages
- Forsterk med 2t4 på høykant på tvers kort bak disse 5cm
- Kontaktene er på hver side av platen, 20 på hver side. De har 0.5cm margin til kantene, er 1cm brede og har 1cm mellom hverandre
- Kontaktene er laget av koppertape, 10mm bredde for alle borsett fra GND som har 30mm bredde
- Kontaktene er festet i bakkant til en bolt, denne bolten går gjennom koppertapen og er festet med en mutter, det skal være en skive og ringkabelsko i mellom. 
- Se "spesifikasjon.png" for hvordan dette kan gjøres
- Bolter kan være limt for å gjøre det enklere
- Koppertape for 24V, 12V, 5V og GND går rundt kanten mellom over og undersiden, se "spesifikasjon.png"
- På toppen av boksen innerst over hele bredden males 5cm dyp 10 sort/hvit bitt jevnt fordelt, altså ca 5cm bred.
- Rør(?)sikringer for 24V, 12V og 5V, verdi for sikringer bestemmes utifra målt resistans i kontakt.
- Bare kontaktene som skal brukes av det eksterne kortet trenger å være implementert.
- Prototypekort med alle kontakter som kan brukes til å teste
- Kontakt for GND på maskinsiden stikker lengere ut for at denne skal skape kontakt først, etter det er strøm kontaktene, og så resten av kontaktene
- DETECTION pin for å fastsette hvilken expansion som er plugget inn. En unik spenning mellom 0V og 5V per expansion. Måles med analog pin på Arduino. Spenning settes med en voltage divider mellom 5V og GND.

- Total bredde :: 51,36cm



** Definisjon av pinner

Pin 1 og 2 er på høyre side sett fra baksiden

| Toppen |           | Bunnen |           |
|    Pin | Funksjon  |    Pin | Funksjon  |
|--------+-----------+--------+-----------|
|      1 | 24V       |      2 | 24V       |
|      3 | 12V       |      4 | 12V       |
|      5 | 5V        |      6 | 5V        |
|      7 | GND       |      8 | GND       |
|      9 | GND       |     10 | GND       |
|     11 | Serial RX |     12 | Serial TX |
|     13 | USB data+ |     14 | USB data- |
|     15 | i2c SDA   |     16 | i2c SCL   |
|     17 | DETECTION |     18 | RESERVED  |
|     19 | RESERVED  |     20 | RESERVED  |
|     21 | GPIO  1   |     22 | GPIO 20   |
|     23 | GPIO  2   |     24 | GPIO 19   |
|     25 | GPIO  3   |     26 | GPIO 18   |
|     27 | GPIO  4   |     28 | GPIO 17   |
|     29 | GPIO  5   |     30 | GPIO 16   |
|     31 | GPIO  7   |     32 | GPIO 14   |
|     33 | GPIO  6   |     34 | GPIO 15   |
|     35 | GPIO  8   |     36 | GPIO 13   |
|     37 | GPIO  9   |     38 | GPIO 12   |
|     39 | GPIO 10   |     40 | GPIO 11   |


** All komunikasjon, kablet og trådløst
- Pinner som definert over
- 10b sort/hvit malt på toppen av boksen, hvit: 1 sort: 0
- Bluetooth-muligheter

** Gjennkjenning av hardware
- 10 bitt malt i sort: 0 eller hvit: 1 fremst på toppen av boksen, 5cm dype og jevnt fordelt.

** Lengde av dataledere
- https://electronics.stackexchange.com/questions/52851/usb-differential-pair-length


** Boltinfo
- Bolt type: DIN 933
- Diameter: M4
- Gjennomgående bolt har lengde 35mm
- Bolt som går gjennom halve flaten er 25mm

** Skive

** Mutter
